print('Quanto dinheiro?')
print(8*2)
print('Desafio')
print('Quanto dinheiro você ganharia se lavasse 12 carros e cobrasse R$ 12,50 por cada lavagem?')
print(12 * 12.50)
print(' =' * 20)
print('Quantos anos?')
print(2025-2000)
print('Desafio')
print(2025-1998)
print(2050-2023)
print(' =' * 20)
print('Variáveis')
print("Em que ano você nasceu?")
nascimento = input()
nascimento= int(nascimento)
print(2025-nascimento)
print("Em 2025 você terá", 2025- nascimento, "anos!")
print(' =' * 20)
print('Desafio: O ano 3000')
print("Em que ano você nasceu?")
nascimento = input()
nascimento= int(nascimento)
print(3000-nascimento)
print("No ano 3000 você terá", 3000- nascimento, "anos!")
print(' =' * 20)
print('Desafio: Sua idade de cachorro ')
print("Qual a sua idade?")
nascimento = input()
nascimento= int(nascimento)
print(nascimento * 7)
print("Se você fosse um cahorro, você teria", nascimento * 7, "anos!")
